
export const faqItems = [
    { value: "item-1", question: "¿Qué idiomas enseñan?", answer: "Ofrecemos programas de alta calidad en Inglés, Francés, Alemán y Portugués. Nuestros cursos están diseñados para diferentes edades y niveles, desde principiantes (A1) hasta avanzados (C1)." },
    { value: "item-2", question: "¿Cuáles son los requisitos para inscribirme?", answer: "Los requisitos varían según el programa. Generalmente, necesitas tu documento de identidad y completar el formulario de inscripción. Para niveles no iniciales, podrías necesitar un examen de clasificación. Consulta la página de 'Proceso de Inscripción' para más detalles." },
    { value: "item-3", question: "¿Ofrecen cursos para niños?", answer: "¡Sí! Tenemos programas de inglés especialmente diseñados para niños desde los 5 años, con metodologías lúdicas y efectivas para cada grupo de edad." },
    { value: "item-4", question: "¿Qué modalidades de estudio tienen?", answer: "Contamos con modalidades presenciales, virtuales, semi-intensivas e intensivas para adaptarnos a tus necesidades y ritmo de vida." },
    { value: "item-5", question: "¿Cómo puedo saber mi nivel de idioma?", answer: "Ofrecemos un examen de clasificación que evalúa tus competencias y te ubica en el nivel adecuado para que aproveches al máximo tu aprendizaje." },
    { value: "item-6", question: "¿Hay descuentos disponibles?", answer: "Sí, contamos con tarifas de 'Proyección Social' que ofrecen descuentos a estudiantes, egresados, y personal de Unillanos, así como a población especial y beneficiarios de convenios. Consulta nuestra página de 'Valores y Tarifas' para más información." },
    { value: "item-7", question: "¿Preparan para exámenes internacionales?", answer: "Sí, ofrecemos talleres especializados para la preparación de exámenes internacionales como IELTS, TOEFL, y DELF, entre otros." },
    { value: "item-8", question: "¿Qué es el Plan B.U.L.L.?", answer: "El Plan Bilingüe Universitario Llanero (B.U.L.L.) es un programa para estudiantes de pregrado de Unillanos que busca fortalecer sus competencias en un segundo idioma como requisito de grado. Ofrecemos los cursos y exámenes necesarios para cumplir con este plan." },
    { value: "item-9", question: "¿Dónde están ubicados?", answer: "Nuestra sede principal del Centro de Idiomas está en el barrio La Grama, en la Carrera 30A No 41B - 39, Villavicencio. También tenemos presencia en otros campus de la universidad." },
    { value: "item-10", question: "¿Cuándo son las próximas inscripciones?", answer: "Las fechas de inscripción se anuncian a través de nuestros canales oficiales. Te recomendamos estar atento a nuestra sección de 'Noticias' y redes sociales para no perderte las convocatorias." },
    { value: "item-11", question: "¿Qué es el Marco Común Europeo de Referencia (MCER)?", answer: "Es el estándar internacional que utilizamos para definir el nivel de competencia lingüística de nuestros estudiantes. Nuestros programas están alineados con los niveles del MCER, desde A1 (Principiante) hasta C1 (Avanzado)." },
    { value: "item-12", question: "¿Puedo homologar niveles de otra institución?", answer: "Sí, es posible. Debes presentar los certificados y contenidos programáticos de la institución anterior para que nuestro comité académico realice un estudio de homologación. Este trámite tiene un costo." },
    { value: "item-13", question: "¿Qué materiales de estudio se utilizan?", answer: "Utilizamos una combinación de libros de texto de editoriales reconocidas, material digital interactivo en nuestra plataforma Moodle y recursos propios desarrollados por nuestros docentes para una experiencia de aprendizaje integral." },
    { value: "item-14", question: "¿Cómo son las evaluaciones?", answer: "Las evaluaciones son continuas e incluyen participación en clase, tareas, proyectos, quices y exámenes parciales y finales. El objetivo es medir el progreso en las cuatro habilidades: habla, escucha, lectura y escritura." },
    { value: "item-15", question: "¿Ofrecen actividades extracurriculares?", answer: "¡Sí! Regularmente organizamos clubes de conversación, talleres culturales, ciclos de cine y eventos temáticos para que practiques el idioma en un ambiente relajado y divertido. ¡Revisa nuestra sección de 'Actividades'!" },
    { value: "item-16", question: "¿Cuál es la duración de cada nivel?", answer: "La duración varía según la intensidad horaria del curso. Los cursos regulares suelen durar un semestre académico, mientras que los intensivos permiten avanzar más rápido. Los detalles específicos se encuentran en el brochure de cada idioma." },
    { value: "item-17", question: "¿Puedo tomar varios idiomas al mismo tiempo?", answer: "Sí, siempre y cuando no haya cruce de horarios y puedas cumplir con la carga académica de cada curso. Es un gran reto, ¡pero posible para estudiantes dedicados!" },
    { value: "item-18", question: "¿Qué pasa si repruebo un nivel?", answer: "Si no apruebas un nivel, deberás repetirlo en el siguiente ciclo académico para poder avanzar. Te recomendamos hablar con tu docente para identificar áreas de mejora y estrategias de estudio." },
    { value: "item-19", question: "¿Hay opciones de financiación o pago a plazos?", answer: "Las políticas de pago son gestionadas por la Tesorería de la Universidad de los Llanos. Te recomendamos contactarlos directamente para conocer las opciones disponibles de financiación y pago." },
    { value: "item-20", question: "¿Recibo un certificado al finalizar?", answer: "Sí, al aprobar cada nivel puedes solicitar un certificado oficial del Centro de Idiomas que acredita las horas cursadas y el nivel alcanzado según el MCER. Este trámite tiene un costo administrativo." }
];
